version: "3.8"

networks:
  integration-tests:
    driver: bridge

services:
  test:
    ports:
      - "5000:5000"
    environment: 
      - "SERVER_PORT=5000"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_USER=postgres"
      - "DB_PASSWORD=pass"
      - "DB_NAME=postgres"
      - "DB_DRIVER=postgres"
      - "APP_KEYSOURCE_RSAKEY_SIZE=2048"
      - "APP_KEYSOURCE_POOL_SIZE=10"
    build:
      context: .
      dockerfile: ./builds/Dockerfile.test
    depends_on: 
      - db
    networks: 
      - integration-tests
  db:
    image: "postgres:alpine"
    restart: on-failure
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment: 
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_DB=postgres"
    networks: 
      - integration-tests
