version: "3.8"
services:
  app:
    ports:
      - "5000:5000"
    environment: 
      - "SERVER_PORT=5000"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_USER=postgres"
      - "DB_PASSWORD=pass"
      - "DB_NAME=gocrypto"
      - "DB_DRIVER=postgres"
      - "APP_KEYSOURCE_RSAKEY_SIZE=2048"
      - "APP_KEYSOURCE_POOL_SIZE=10"
    build:
      context: .
    depends_on: 
      - db
  db:
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: pass
