name: Integration tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run integration
        run: make test-full
